AWSTemplateFormatVersion: "2010-09-09"
Description: Define what is needed for Fargate.

Outputs:
  FargateECSClusterArn: 
    Value: !GetAtt Cluster.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-FargateClusterArn"
  FargateECSTaskDefinition: 
    Value: !Ref TaskDefinition
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-FargateTaskDefinition"
  FargateExecutionRoleArn: 
    Value: !GetAtt ExecutionRole.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-FargateExecutionRoleArn"

Resources:
  FargateECSRepo:
    Type: "AWS::ECR::Repository"

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: fargate-cluster

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/ecs-tasks-fargate
      RetentionInDays: 1

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: '512'
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: fargate-container
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FargateECSRepo}:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/ecs-tasks-fargate
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Sid: 'ECS'
          Principal:
            Service:
              - ecs-tasks.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
