AWSTemplateFormatVersion: "2010-09-09"
Description: Define what is needed for Fargate. This template import values from 'docker-registry-stack' stack.

Outputs:
  FargateECSClusterArn: 
    Value: !GetAtt Cluster.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-FargateClusterArn"
  FargateECSTaskDefinition: 
    Value: !Ref TaskDefinition
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-FargateTaskDefinition"
  FargateExecutionRoleArn: 
    Value: !GetAtt ExecutionRole.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-FargateExecutionRoleArn"

Resources:
  FargateECSRepo:
    Type: "AWS::ECR::Repository"

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: fargate-cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      # Name of the task definition. Subsequent versions of the task definition are grouped together under this name.
      Family: fargate-task-definition
      # awsvpc is required for Fargate
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
      # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
      # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
      # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
      # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
      Cpu: 256
      # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
      # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
      # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
      # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
      # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
      Memory: 0.5GB
      # A role needed by ECS.
      # "The ARN of the task execution role that containers in this task can assume. All containers in this task are granted the permissions that are specified in this role."
      # "There is an optional task execution IAM role that you can specify with Fargate to allow your Fargate tasks to make API calls to Amazon ECR."
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: fargate-container
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FargateECSRepo}:latest

  # A role needed by ECS
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
