AWSTemplateFormatVersion: "2010-09-09"
Description: Stack that creates a VPC for the ECS Cluster that will run Fargate and its Tasks.
  It also creates the needed subnets, internet gateway and route table.
  Values needed by other stacks are exported.

Outputs:
  ECSSubnet: 
    Value: !Ref FargateSubnet
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SubnetID"
  ECSSecGroup: 
    Value: !Ref FargateSG
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SecurityGroupID"

Resources:
  FargateVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

  FargateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock : 10.0.0.0/24
      VpcId: !Ref FargateVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

  FargateIGW:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

  FargateAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FargateVPC
      InternetGatewayId: !Ref FargateIGW

  FargateRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref FargateVPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

  FargateRoute:
    Type: "AWS::EC2::Route"
    DependsOn: FargateAttachGateway
    Properties:
      RouteTableId: !Ref FargateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FargateIGW

  FargateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FargateSubnet
      RouteTableId: !Ref FargateRouteTable

  FargateSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub Generated by ${AWS::StackName}
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: 127.0.0.1/32
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}
      VpcId: !Ref FargateVPC